### ISSUE TITLE
As a user, when I generate passwords inside the tooltip, what's the meaning of the cursor and the intended functionality (if any)? #Help #Question

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/ui#19]
Transferred from https://github.com/buttercup/buttercup-desktop/issues/714

Regards

**Comment by perry-mitchell** [comment]
To extend on this: The question was answered previously - The cursor indicates that the password can be copied, single-click. Currently this doesn't work.

**Comment by ldexterldesign** [comment]
Is there a reason this issue is closed?

Copying password still not working for me

Sincerely

**Comment by perry-mitchell** [comment]
@ldexterldesign This was a question, not a bug. If you're experiencing a bug for copying then could you create a new issue? Sorry this has taken so long. I've not reproduced any copy issues in the new UI, however.. The desktop isn't currently using this library either.

**Comment by ldexterldesign** [comment]
Thanks for reply

Hmm, well this still isn't working in macOS for me

I'm ambivalent about whether it's fixed or not as I don't use the feature that much (perhaps I would if it worked). As long as you're aware of the issue that's the main thing.

What's this "new" UI you speak of?

Hope to hear back

Sincerely
