### ISSUE TITLE
Capital letter in Spanish translation

### ISSUE THREAD

**Issue by RafaMunoz** [buttercup/ui#76]
Hi,

In the file src/i18n/translations/es.json the value of key  "cta" is with two letter capital and should be only the first "Nueva entrada".

```
# BAD
{
"new-entry": {
    "cta": "NUeva entrada"
  }
```

```
# GOOD
{
"new-entry": {
    "cta": "Nueva entrada"
  }
```

**Comment by perry-mitchell** [comment]
Fixed by #77
